package com.careemwebapp;

/**
 * Created by alex on 5.11.15.
 */
public enum SuggestionType {

    SUGGESTION_TYPE_HEADER_SUGGESTION,
    SUGGESTION_TYPE_HEADER_FAVORITE,
    SUGGESTION_TYPE_HEADER_HISTORY,
    SUGGESTION_TYPE_ADDRESS_ELEMENT,
    SUGGESTION_TYPE_FAVORITE_ELEMENT,
    SUGGESTION_TYPE_PLACE_ELEMENT,
    SUGGESTION_TYPE_AIRPORT_ELEMENT

    }
